# Generated by Django 4.0.3 on 2022-03-22 16:49

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCall',
            fields=[
                ('meeting_id', models.UUIDField(default=api.models.get_uuid_emergency, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('meeting_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
