# Generated by Django 4.0.3 on 2022-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emergencycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycall',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
